// 管理面板的单文件页面。
//
// 不引前端框架, 也不外链任何 CDN: 服务端承诺零依赖、可离线部署,
// 页面一旦依赖 CDN 就等于把可用性押在别人身上。
// 因此这里是「一份 HTML + 一段原生 JS」, 由服务端直接吐出。

export const ADMIN_PAGE = [
  '<!doctype html><html lang="zh-CN"><head>',
  '<meta charset="utf-8">',
  '<meta name="viewport" content="width=device-width,initial-scale=1">',
  '<title>UMIGURI 管理面板</title>',
  '<style>',
  '  :root { color-scheme: dark; }',
  '  * { box-sizing: border-box; }',
  '  body {',
  '    margin: 0; min-height: 100vh; padding: 24px 16px;',
  '    background: #0f1115; color: #e8eaed;',
  '    font: 15px/1.6 system-ui, -apple-system, "Segoe UI", "Noto Sans SC", sans-serif;',
  '  }',
  '  .wrap { max-width: 980px; margin: 0 auto; }',
  '  h1 { font-size: 22px; margin: 0 0 4px; }',
  '  .sub { color: #9aa0a6; font-size: 13px; margin-bottom: 22px; }',
  '  .card {',
  '    background: #171a21; border: 1px solid #262a33; border-radius: 12px;',
  '    padding: 18px 20px; margin-bottom: 16px;',
  '  }',
  '  .card h2 { font-size: 15px; margin: 0 0 12px; color: #9aa0a6; font-weight: 600; }',
  '  label { display: block; font-size: 13px; color: #9aa0a6; margin: 10px 0 4px; }',
  '  input {',
  '    width: 100%; max-width: 340px; padding: 9px 11px; border-radius: 8px;',
  '    border: 1px solid #303743; background: #0f1115; color: #e8eaed;',
  '    font: inherit; font-size: 14px;',
  '  }',
  '  input:focus { outline: none; border-color: #5b8def; }',
  '  button {',
  '    padding: 9px 16px; border-radius: 8px; border: 1px solid #303743;',
  '    background: #222834; color: #e8eaed; font: inherit; font-size: 14px;',
  '    cursor: pointer;',
  '  }',
  '  button:hover:not(:disabled) { background: #2b3342; }',
  '  button:disabled { opacity: .5; cursor: default; }',
  '  button.primary { background: #2f5fd0; border-color: #2f5fd0; }',
  '  button.primary:hover:not(:disabled) { background: #3a6ee0; }',
  '  button.danger { border-color: #6b2b34; color: #ff9aa5; }',
  '  button.danger:hover:not(:disabled) { background: #3a1f24; }',
  '  button.small { padding: 5px 10px; font-size: 13px; }',
  '  .row { display: flex; gap: 10px; align-items: flex-end; flex-wrap: wrap; }',
  '  .msg { margin-top: 12px; font-size: 14px; min-height: 1.4em; }',
  '  .msg.err { color: #ff8a8a; }',
  '  .msg.ok { color: #7ee0a1; }',
  '  table { width: 100%; border-collapse: collapse; font-size: 14px; }',
  '  th, td { text-align: left; padding: 9px 8px; border-bottom: 1px solid #232833; }',
  '  th { color: #9aa0a6; font-weight: 600; font-size: 13px; }',
  '  tr:last-child td { border-bottom: none; }',
  '  .tag {',
  '    display: inline-block; padding: 1px 7px; border-radius: 999px;',
  '    font-size: 12px; border: 1px solid #303743; color: #9aa0a6;',
  '  }',
  '  .tag.warn { border-color: #7a5a1e; color: #ffcd6b; }',
  '  .tag.ok { border-color: #2b5c3c; color: #7ee0a1; }',
  '  .qr {',
  '    display: block; width: 240px; height: 240px; margin: 10px 0 4px;',
  '    background: #fff; border-radius: 8px; padding: 8px;',
  '  }',
  '  .secret {',
  '    font-family: ui-monospace, Consolas, monospace; font-size: 17px;',
  '    letter-spacing: .09em; background: #0f1115; border: 1px solid #303743;',
  '    border-radius: 8px; padding: 12px; margin: 6px 0; word-break: break-all;',
  '  }',
  '  .hint { color: #9aa0a6; font-size: 13px; }',
  '  .mono { font-family: ui-monospace, Consolas, monospace; font-size: 13px; }',
  '  .cards { margin: 8px 0 4px 0; padding: 10px 12px; background: #0f1115;',
  '           border: 1px solid #262a33; border-radius: 8px; }',
  '  .cards .line { display: flex; gap: 10px; align-items: center; padding: 4px 0; }',
  '  .cards .line .grow { flex: 1; }',
  '  .revoked { color: #6b7280; text-decoration: line-through; }',
  '  .hidden { display: none !important; }',
  '</style>',
  '</head><body><div class="wrap">',
  '',
  '  <section id="loginView">',
  '    <h1>UMIGURI 管理面板</h1>',
  '    <div class="sub">用管理员令牌登录。令牌来自服务端启动时打印的内容, 或环境变量 UMIGURI_ADMIN_TOKEN。</div>',
  '    <div class="card">',
  '      <h2>管理员登录</h2>',
  '      <label for="token">管理员令牌</label>',
  '      <input id="token" type="password" autocomplete="current-password" placeholder="粘贴管理员令牌">',
  '      <div class="row" style="margin-top:14px">',
  '        <button class="primary" id="loginBtn">登录</button>',
  '      </div>',
  '      <div class="msg" id="loginMsg"></div>',
  '    </div>',
  '  </section>',
  '',
  '  <section id="mainView" class="hidden">',
  '    <h1>UMIGURI 管理面板</h1>',
  '    <div class="sub" id="headerSub">已登录</div>',
  '',
  '    <div class="card">',
  '      <h2>建号</h2>',
  '      <div class="row">',
  '        <div>',
  '          <label for="newUser">用户名(3~24 位, 仅字母/数字/下划线/连字符)</label>',
  '          <input id="newUser" placeholder="例如 playerA">',
  '        </div>',
  '        <button class="primary" id="createBtn">创建账号</button>',
  '      </div>',
  '      <div class="msg" id="createMsg"></div>',
  '      <div id="secretBox" class="hidden">',
  '        <div class="hint" style="margin-top:10px">让玩家用验证器 App(Google Authenticator 等)扫下面的二维码, 一下就绑好了。二维码与密钥只在此刻显示一次, 之后无法再次查看。</div>',
  '        <img id="secretQr" class="qr" alt="TOTP 绑定二维码">',
  '        <div class="hint" id="qrHint">扫不了码? 也可以让玩家在验证器 App 里选「手动输入密钥」手抄下面这把密钥, 或者把 otpauth 链接发给他。</div>',
  '        <div class="secret" id="secretText"></div>',
  '        <div class="row">',
  '          <button class="small" id="copySecret">复制密钥</button>',
  '          <a class="hint" id="otpauthLink" href="#" style="align-self:center">otpauth 链接</a>',
  '        </div>',
  '      </div>',
  '    </div>',
  '',
  '    <div class="card">',
  '      <h2>账号列表</h2>',
  '      <div id="usersBox" class="hint">加载中…</div>',
  '    </div>',
  '',
  '    <div class="card">',
  '      <button class="danger small" id="logoutBtn">退出登录</button>',
  '    </div>',
  '  </section>',
  '</div>',
  '',
  '<script>',
  'var state = { users: [] };',
  'var expanded = {};',
  '',
  'function $(id) { return document.getElementById(id); }',
  '',
  'function esc(s) {',
  '  var d = document.createElement("div");',
  '  d.textContent = String(s);',
  '  return d.innerHTML;',
  '}',
  '',
  'function setMsg(el, text, kind) {',
  '  el.textContent = text || "";',
  '  el.className = "msg" + (kind ? " " + kind : "");',
  '}',
  '',
  'async function api(path, opts) {',
  '  var res = await fetch(path, Object.assign({ credentials: "same-origin" }, opts || {}));',
  '  var data = null;',
  '  try { data = await res.json(); } catch (e) { data = null; }',
  '  if (!res.ok || (data && data.ok === false)) {',
  '    var err = new Error((data && data.error) || ("请求失败 (" + res.status + ")"));',
  '    err.code = data && data.code;',
  '    throw err;',
  '  }',
  '  return data || {};',
  '}',
  '',
  'function showSecret(username, secret, url, qr) {',
  '  $("secretBox").classList.remove("hidden");',
  '  var img = $("secretQr");',
  '  var qrHint = $("qrHint");',
  '  if (qr) {',
  '    img.src = qr;',
  '    img.classList.remove("hidden");',
  '    qrHint.classList.remove("hidden");',
  '  } else {',
  '    img.removeAttribute("src");',
  '    img.classList.add("hidden");',
  '    qrHint.classList.add("hidden");',
  '  }',
  '  var grouped = (String(secret).match(/.{1,4}/g) || []).join(" ");',
  '  $("secretText").textContent = grouped;',
  '  $("secretText").dataset.raw = secret;',
  '  var link = $("otpauthLink");',
  '  link.href = url;',
  '  link.textContent = "otpauth 链接: " + username;',
  '}',
  '',
  'function renderUsers() {',
  '  var box = $("usersBox");',
  '  if (!state.users.length) {',
  '    box.innerHTML = "还没有账号, 用上面的表单建一个。";',
  '    box.className = "hint";',
  '    return;',
  '  }',
  '  var html = \'<table><thead><tr><th>用户名</th><th>显示名</th><th>偏差</th><th>验证器</th><th>卡</th><th></th></tr></thead><tbody>\';',
  '  state.users.forEach(function (u) {',
  '    html += "<tr>";',
  '    html += \'<td class="mono">\' + esc(u.username) + "</td>";',
  '    html += "<td>" + esc(u.displayName) + "</td>";',
  '    html += "<td>" + u.rating + "</td>";',
  '    html += "<td>" + (u.totpBound ? \'<span class="tag ok">已绑定</span>\' : \'<span class="tag warn">未绑定</span>\') + "</td>";',
  '    html += "<td>" + u.cardCount + "</td>";',
  '    html += \'<td style="white-space:nowrap">\';',
  '    html += \'<button class="small" data-act="cards" data-id="\' + u.id + \'">卡号</button> \';',
  '    html += \'<button class="small" data-act="issue" data-id="\' + u.id + \'">发卡</button> \';',
  '    html += \'<button class="small" data-act="reset" data-id="\' + u.id + \'">重置验证器</button>\';',
  '    html += "</td></tr>";',
  '    if (expanded[u.id]) {',
  '      html += \'<tr><td colspan="6">\' + renderCards(u) + "</td></tr>";',
  '    }',
  '  });',
  '  html += "</tbody></table>";',
  '  box.className = "";',
  '  box.innerHTML = html;',
  '}',
  '',
  'function renderCards(u) {',
  '  var cs = u.cards || [];',
  '  if (!cs.length) return \'<div class="cards hint">该账号还没有卡号。</div>\';',
  '  var html = \'<div class="cards">\';',
  '  cs.forEach(function (c) {',
  '    var label = c.label ? " (" + esc(c.label) + ")" : "";',
  '    html += \'<div class="line">\';',
  '    html += \'<span class="mono grow\' + (c.revokedAt ? " revoked" : "") + \'">\' + esc(c.cardId) + label + "</span>";',
  '    if (c.revokedAt) {',
  '      html += \'<span class="tag">已吊销</span>\';',
  '    } else {',
  '      html += \'<span class="tag ok">有效</span>\';',
  '      html += \'<button class="small danger" data-act="revoke" data-id="\' + u.id + \'" data-card="\' + esc(c.cardId) + \'">吊销</button>\';',
  '    }',
  '    html += "</div>";',
  '  });',
  '  html += "</div>";',
  '  return html;',
  '}',
  '',
  'async function loadUsers() {',
  '  try {',
  '    var data = await api("/admin-panel/users");',
  '    state.users = data.users || [];',
  '    $("headerSub").textContent = "已登录 · 共 " + state.users.length + " 个账号";',
  '    renderUsers();',
  '  } catch (e) {',
  '    if (e.code === "admin_panel_unauthorized") { showLogin(); return; }',
  '    $("usersBox").className = "msg err";',
  '    $("usersBox").textContent = e.message;',
  '  }',
  '}',
  '',
  'function showLogin() {',
  '  $("loginView").classList.remove("hidden");',
  '  $("mainView").classList.add("hidden");',
  '}',
  '',
  'function showMain() {',
  '  $("loginView").classList.add("hidden");',
  '  $("mainView").classList.remove("hidden");',
  '  loadUsers();',
  '}',
  '',
  '$("loginBtn").addEventListener("click", async function () {',
  '  var btn = $("loginBtn");',
  '  btn.disabled = true;',
  '  setMsg($("loginMsg"), "登录中…");',
  '  try {',
  '    await api("/admin-panel/login", {',
  '      method: "POST",',
  '      headers: { "content-type": "application/json" },',
  '      body: JSON.stringify({ token: $("token").value })',
  '    });',
  '    $("token").value = "";',
  '    setMsg($("loginMsg"), "");',
  '    showMain();',
  '  } catch (e) {',
  '    setMsg($("loginMsg"), e.message, "err");',
  '  } finally {',
  '    btn.disabled = false;',
  '  }',
  '});',
  '',
  '$("token").addEventListener("keydown", function (ev) {',
  '  if (ev.key === "Enter") $("loginBtn").click();',
  '});',
  '',
  '$("logoutBtn").addEventListener("click", async function () {',
  '  try { await api("/admin-panel/logout", { method: "POST" }); } catch (e) {}',
  '  showLogin();',
  '});',
  '',
  '$("createBtn").addEventListener("click", async function () {',
  '  var name = $("newUser").value.trim();',
  '  if (!name) { setMsg($("createMsg"), "请先填用户名", "err"); return; }',
  '  var btn = $("createBtn");',
  '  btn.disabled = true;',
  '  setMsg($("createMsg"), "创建中…");',
  '  try {',
  '    var data = await api("/admin-panel/users", {',
  '      method: "POST",',
  '      headers: { "content-type": "application/json" },',
  '      body: JSON.stringify({ username: name })',
  '    });',
  '    setMsg($("createMsg"), "已创建账号 " + data.user.username, "ok");',
  '    showSecret(data.user.username, data.totpSecret, data.otpauthUrl, data.otpauthQr);',
  '    $("newUser").value = "";',
  '    loadUsers();',
  '  } catch (e) {',
  '    setMsg($("createMsg"), e.message, "err");',
  '  } finally {',
  '    btn.disabled = false;',
  '  }',
  '});',
  '',
  '$("copySecret").addEventListener("click", async function () {',
  '  var raw = $("secretText").dataset.raw || "";',
  '  var self = this;',
  '  try {',
  '    await navigator.clipboard.writeText(raw);',
  '    self.textContent = "已复制";',
  '    setTimeout(function () { self.textContent = "复制密钥"; }, 1500);',
  '  } catch (e) {',
  '    self.textContent = "复制失败, 请手动选中";',
  '  }',
  '});',
  '',
  'async function refreshCards(id) {',
  '  var data = await api("/admin-panel/users/" + id + "/cards");',
  '  var u = state.users.filter(function (x) { return x.id === id; })[0];',
  '  if (u) u.cards = data.cards || [];',
  '}',
  '',
  '$("usersBox").addEventListener("click", async function (ev) {',
  '  var btn = ev.target && ev.target.closest ? ev.target.closest("button[data-act]") : null;',
  '  if (!btn) return;',
  '  var id = Number(btn.dataset.id);',
  '  var act = btn.dataset.act;',
  '  btn.disabled = true;',
  '  try {',
  '    if (act === "cards") {',
  '      expanded[id] = !expanded[id];',
  '      if (expanded[id]) await refreshCards(id);',
  '      renderUsers();',
  '    } else if (act === "issue") {',
  '      var r = await api("/admin-panel/users/" + id + "/cards", {',
  '        method: "POST", headers: { "content-type": "application/json" }, body: "{}"',
  '      });',
  '      alert("已发卡: " + r.card.cardId);',
  '      expanded[id] = true;',
  '      await loadUsers();',
  '      await refreshCards(id);',
  '      renderUsers();',
  '    } else if (act === "reset") {',
  '      if (!confirm("确定重置该账号的验证器? 旧密钥立刻失效, 玩家需要用新密钥重新绑定。")) return;',
  '      var r2 = await api("/admin-panel/users/" + id + "/totp-reset", { method: "POST" });',
  '      showSecret(r2.user.username, r2.totpSecret, r2.otpauthUrl, r2.otpauthQr);',
  '      alert("已重置。新二维码显示在「建号」区域下方, 请立刻交给玩家扫码。");',
  '      loadUsers();',
  '    } else if (act === "revoke") {',
  '      if (!confirm("确定吊销这张卡? 吊销后立刻无法用该卡登录。")) return;',
  '      await api("/admin-panel/cards/" + encodeURIComponent(btn.dataset.card), { method: "DELETE" });',
  '      await loadUsers();',
  '      await refreshCards(id);',
  '      renderUsers();',
  '    }',
  '  } catch (e) {',
  '    alert(e.message);',
  '  } finally {',
  '    btn.disabled = false;',
  '  }',
  '});',
  '',
  '(async function boot() {',
  '  try {',
  '    await api("/admin-panel/me");',
  '    showMain();',
  '  } catch (e) {',
  '    showLogin();',
  '  }',
  '})();',
  '</script>',
  '</body></html>',
].join("\n");
